POST http://localhost:8080/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8080/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8080/user/getAll
Content-Type: application/json

###

POST http://localhost:8080/user/editUser
Content-Type: application/json 

{
    "userId" : "6346044aeaec8d57081e85ae"
}

###
GET  http://localhost:8080/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###
GET  http://localhost:8080/user/getUserById
Content-Type: application/json 

{
    "userId" : "634edb2a16710b2cda6fb370"
}