###
GET http://localhost:8085/following
Content-Type: application/json

###
GET http://localhost:8085/followers
Content-Type: application/json

###
POST http://localhost:8085/followers/follow
Content-Type: application/json 

{
    "userId" : "Doodle",
    "targetUserId" : "John"
}

###
POST http://localhost:8085/followers/unfollow
Content-Type: application/json 

{
    "userId" : "John",
    "targetUserId" : "Jerry"
}

###
GET http://localhost:8085/followers/Bryan
Accept: application/json 

###
GET http://localhost:8085/following/Jackson
Accept: application/json 