
GET http://localhost:8085/following
Content-Type: application/json

###
GET http://localhost:8085/followers
Content-Type: application/json

###
POST http://localhost:8085/followers/follow
Content-Type: application/json 

{
    "userId" : "Jackson",
    "targetUserId" : "Jerry"
}

###
POST http://localhost:8085/followers/followUser
Content-Type: application/json 

{
    "userId" : "Larry",
    "targetUserId" : "John"
}

###
DELETE http://localhost:8085/followers/deleteFollower
Content-Type: application/json 

{
    "userId" : "John",
    "targetUserId" : "Larry"
}

###
GET http://localhost:8085/followers/Bryan
Accept: application/json 

###


GET http://localhost:8085/following/Jackson
Accept: application/json 

###
