Get http://localhost:8089/comments/comment/
Content-Type: application/json
###
GET http://localhost:8089/comments/comment/:id
Content-Type: application/json
###
POST http://localhost:8089/comments/comment/add 
Content-Type: application/json

{
      "username": "",
      "commentContent": ""
}
###
DELETE http://localhost:8089/comments/comment/:id
Content-Type: application/json

###
Put http://localhost:8089/comments/comment/update/:id 
Content-Type: application/json

{
  "commentContent": ""
}
###
Post http://localhost:8089/comments/comment/reply/:id 
Content-Type: application/json

{
      "commentContent": "Hello World!",
}
###

